name: veldoc

services:
  veldoc:
    image: ghcr.io/sean-59/veldoc:latest
    container_name: veldoc
    restart: unless-stopped
    ports:
      - "6006:6006"
    networks:
      - veldoc-network

networks:
  veldoc-network:
    name: veldoc-network
    driver: bridge
